name: Cloudflare Block Ads Cleanup

on:
  workflow_dispatch:

jobs:
  delete-block-ads:
    runs-on: ubuntu-latest

    env:
      API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Make script executable
        run: chmod +x block_ads_delete.sh

      - name: Run Cloudflare block ads delete script
        run: ./block_ads_delete.sh
