name: Permanent Log Sync

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  sync_logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run Harvester
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          GOOGLE_SCRIPT_URL: ${{ secrets.GOOGLE_SCRIPT_URL }}
        run: |
          chmod +x log_harvester.sh
          ./log_harvester.sh
